- name: Guillaume Jacquenot
  email: guillaume.jacquenot@gmail.com
  alternate_emails:
  - Gjacquenot@users.noreply.github.com
  num_commits: 37
  first_commit: 2018-01-03 06:01:35
  github: Gjacquenot
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 49
  first_commit: 2015-05-13 16:20:53
- name: Sam Mellor
  email: github@u2ft.me
  alternate_emails:
  - U2Ft@users.noreply.github.com
  num_commits: 3
  first_commit: 2018-01-04 10:19:12
  github: U2Ft
- name: Kacper Kowalik
  email: xarthisius.kk@gmail.com
  num_commits: 1
  first_commit: 2015-08-20 15:36:49
  github: Xarthisius
- name: atmyers
  email: atmyers2@gmail.com
  num_commits: 6
  first_commit: 2015-05-15 21:28:00
  github: atmyers
- name: Dag Wästberg
  email: dwastberg@gmail.com
  num_commits: 11
  first_commit: 2017-04-05 17:02:02
  github: dwastberg
- name: Matthew Turk
  email: matthewturk@gmail.com
  num_commits: 10
  first_commit: 2015-05-13 16:42:25
